_target_: instant_avatar.datasets.mydemo.MYDataModule
name: mydemo
subject: 'James'
gender: male
opt:
  dataroot: ./data/mydemo/${dataset.subject}/
  subject: ${dataset.subject}
  train:
    num_workers: 8
    batch_size: 1
    start: 0
    end: 190
    skip: 1
    downscale: 2
    sampler: ${sampler}
    fitting: ${model.opt.optimize_SMPL.enable}
    refine: ${model.opt.optimize_SMPL.is_refine}
  val:
    num_workers: 8
    batch_size: 1
    start: 0
    end: 1
    skip: 1
    downscale: 2
  test:
    num_workers: 8
    batch_size: 1
    start: 0
    end: 1
    skip: 1
    downscale: 2
